---
# Update apt packages
- name: Update apt packages
  become: yes
  apt: 
    update_cache=yes

# Upgrade apt packages
- name: Upgrade apt packages
  become: yes
  apt: 
    upgrade=dist
    
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /root/test
    state: directory
    mode: '0755'
